backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'news'
    label: 'News'
    format: 'json'
    folder: 'assets/content/news'
    create: true
    slug: '{{month}}-{{day}}-{{year}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', allow_multiple: true, widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    format: 'json'
    folder: "assets/content/pages" # The path to the folder where the documents are stored
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Menu Icon', name: 'icon', widget: 'string', default: 'home', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Album"
        name: "albumRel"
        widget: "relation"
        collection: "album"
        searchFields: ["title", "desc"]
        valueField: "title"
        displayFields: ["title"]
        required: true
  - name: "album" # Used in routes, e.g., /admin/collections/blog
    label: "Album" # Used in the UI
    format: 'json'
    folder: "assets/content/album" # The path to the folder where the documents are stored
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', required: true }
      - { label: 'Description', name: 'desc', required: false }
      - { label: 'Style', name: 'style', required: false }
      - label: "Slides"
        name: "slides"
        widget: "list"
        fields:
          - { label: 'Title', name: 'title', required: true }
          - { label: 'Alt', name: 'alt', required: false }
          - { label: 'Image', name: 'image', widget: 'image', required: false}
          - { label: 'Video', name: 'video', widget: 'string', required: false}
          - { label: 'Caption', name: 'caption', widget: 'markdown', required: false }
  - name: "albums" # this will replace "album"
    label: "Albums"
    format: 'json'
    folder: "assets/content/albums"
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', required: true }
      - { label: 'Description', name: 'desc', required: false }
      - { label: 'Style', name: 'style', required: false }
      - label: "Media"
        name: "media"
        widget: "list"
        multiple: true
        collection: "album"
        searchFields: ["title", "desc", "slug"]
        valueField: "slug"
        displayFields: ["title"]
        required: true
  - name: "media" # this will be used in albums
    label: "media" # Used in the UI
    format: 'json'
    folder: "assets/content/media" # The path to the folder where the documents are stored
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: "Items"
        name: "items"
        widget: "list"
        multiple: false
        fields:
          - { label: 'Title', name: 'title', required: true }
          - { label: 'Alt', name: 'alt', required: false }
          - { label: 'Image', name: 'image', widget: 'image', required: false}
          - { label: 'Video', name: 'video', widget: 'string', required: false}
          - { label: 'Caption', name: 'caption', widget: 'markdown', required: false }
  - name: "page2" # Used in routes, e.g., /admin/collections/blog
    label: "Single Use Data Stuctures" # Used in the UI
    format: 'json'
    create: false
    slug: '{{slug}}'
    files:
      - label: "Home Page"
        name: "homepage"
        file: "assets/content/page2/homepage.json"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Featured Image', name: 'thumbnail', allow_multiple: true, widget: 'image', required: false }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Menu Order"
        name: "menuorder"
        file: "assets/content/page2/menuorder.json"
        editor:
          preview: false
        fields:
          - label: "Order"
            name: "order"
            widget: "list"
            multiple: false
            collection: "page"
            searchFields: ["title", "slug"]
            valueField: "title"
            displayFields: ["title"]
            required: true
      - label: "Scheduling Page"
        name: "scheduling"
        file: "assets/content/page2/scheduling.json"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Days to Schedule', name: 'numOfDays', widget: 'number' }
          - label: "Scheduling Start Date"
            name: "startDay"
            widget: "select"
            options:
              - { label: "Monday", value: 1 }
              - { label: "Tuesday", value: 2 }
              - { label: "Wednesday", value: 3 }
              - { label: "Thursday", value: 4 }
              - { label: "Friday", value: 5 }
              - { label: "Saturday", value: 6 }
              - { label: "Sunday", value: 7 }

