backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'news'
    label: 'News'
    format: 'json'
    folder: 'assets/content/news'
    create: true
    slug: '{{month}}-{{day}}-{{year}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', allow_multiple: true, widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    format: 'json'
    folder: "assets/content/pages" # The path to the folder where the documents are stored
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Menu Icon', name: 'icon', widget: 'string', default: 'home', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', allow_multiple: true, widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "album" # Used in routes, e.g., /admin/collections/blog
    label: "Album" # Used in the UI
    format: 'json'
    folder: "assets/content/album" # The path to the folder where the documents are stored
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', required: true }
      - { label: 'Description', name: 'alt', required: false }
      - { label: 'Style', name: 'style', required: false }
      - label: "Slides"
        name: "slides"
        widget: "list"
        fields:
          - { label: 'Title', name: 'title', required: true }
          - { label: 'Alt', name: 'alt', required: false }
          - { label: 'Image', name: 'image', widget: 'image', required: false}
          - { label: 'Video', name: 'video', widget: 'string', required: false}
          - { label: 'Caption', name: 'caption', widget: 'markdown', required: false }

